import React from 'react';
import PropTypes from 'prop-types';
import backendRequest from '../api/backendRequest';
import '../css/site.css';

class PlaylistBuilder extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            saving: false,
            saved: false,
            savedPlaylistUrl: '',
            error: '',
            dragIndex: null,
            dragOverIndex: null
        };
        this.handleSave = this.handleSave.bind(this);
        this.removeTrack = this.removeTrack.bind(this);
    }

    handleDragStart = (e, index) => {
        this.setState({ dragIndex: index });
        e.dataTransfer.effectAllowed = 'move';
        e.dataTransfer.setData('text/plain', index);
        // make the dragged row semi-transparent after a tick
        setTimeout(() => { if (e.target) e.target.style.opacity = '0.4'; }, 0);
    };

    handleDragEnd = (e) => {
        e.target.style.opacity = '1';
        this.setState({ dragIndex: null, dragOverIndex: null });
    };

    handleDragOver = (e, index) => {
        e.preventDefault();
        e.dataTransfer.dropEffect = 'move';
        if (this.state.dragOverIndex !== index) {
            this.setState({ dragOverIndex: index });
        }
    };

    handleDrop = (e, toIndex) => {
        e.preventDefault();
        const fromIndex = this.state.dragIndex;
        if (fromIndex !== null && fromIndex !== toIndex) {
            this.props.onReorder(fromIndex, toIndex);
        }
        this.setState({ dragIndex: null, dragOverIndex: null });
    };

    handleSave() {
        const { playlistTracks, playlistName, playlistDescription, playlistIsPublic } = this.props;

        if (!playlistName.trim()) {
            this.setState({ error: 'Please enter a playlist name.' });
            return;
        }
        if (playlistTracks.length === 0) {
            this.setState({ error: 'Add some tracks to your playlist first.' });
            return;
        }

        this.setState({ saving: true, error: '' });

        backendRequest.post('createPlaylist', {
            name: playlistName,
            description: playlistDescription || 'Generated by TeraHz',
            isPublic: playlistIsPublic
        }, (playlistData) => {
            if (playlistData.error) {
                this.setState({ saving: false, error: 'Failed to create playlist. Make sure you\'re logged in.' });
                return;
            }

            const trackUris = playlistTracks.map(t => 'spotify:track:' + t.id);
            backendRequest.post('addTracksToPlaylist', {
                playlistId: playlistData.id,
                trackUris: trackUris
            }, (addData) => {
                if (addData.error) {
                    this.setState({ saving: false, error: 'Playlist created but failed to add tracks.' });
                    return;
                }
                this.setState({
                    saving: false,
                    saved: true,
                    savedPlaylistUrl: playlistData.external_urls ? playlistData.external_urls.spotify : ''
                });
            });
        });
    }

    removeTrack(trackId) {
        this.props.onRemoveTrack(trackId);
    }

    render() {
        const { playlistTracks, authenticated, playlistName, playlistDescription, playlistIsPublic, onNameChange, onDescChange, onPublicChange, onClear, onClose } = this.props;
        const { saving, saved, savedPlaylistUrl, error } = this.state;

        const totalDuration = playlistTracks.reduce((sum, t) => sum + (t.duration_ms || 0), 0);
        const totalMinutes = Math.floor(totalDuration / 60000);

        return (
            <div className="playlistBuilder">
                <h3 className="playlistBuilderTitle">Playlist Builder</h3>
                <p className="playlistBuilderSubtitle">
                    {playlistTracks.length} track{playlistTracks.length !== 1 ? 's' : ''} · ~{totalMinutes} minutes
                </p>

                {saved && (
                    <div className="playlistSavedBanner">
                        Playlist saved to Spotify!
                        {savedPlaylistUrl && (
                            <a href={savedPlaylistUrl} target="_blank" rel="noopener noreferrer" className="openSpotifyLink">
                                Open in Spotify →
                            </a>
                        )}
                        <button className="newPlaylistBtn" onClick={() => { this.setState({ saved: false, savedPlaylistUrl: '' }); onClear(); }}>
                            Start Fresh
                        </button>
                    </div>
                )}

                {!saved && (
                    <React.Fragment>
                        <div className="playlistForm">
                            <input
                                type="text"
                                className="playlistNameInput"
                                placeholder="Playlist name..."
                                value={playlistName}
                                onChange={(e) => onNameChange(e.target.value)}
                            />
                            <textarea
                                className="playlistDescInput"
                                placeholder="Description (optional)"
                                value={playlistDescription}
                                onChange={(e) => onDescChange(e.target.value)}
                                rows={2}
                            />
                            <label className="publicToggle">
                                <input
                                    type="checkbox"
                                    checked={playlistIsPublic}
                                    onChange={(e) => onPublicChange(e.target.checked)}
                                />
                                Public playlist
                            </label>
                        </div>

                        {error && <div className="playlistError">{error}</div>}

                        {playlistTracks.length > 0 && (
                            <div className="playlistListHeader">
                                <button className="clearAllBtn" onClick={onClear}>Clear All</button>
                            </div>
                        )}

                        <div className="playlistTrackList">
                            {playlistTracks.length === 0 && (
                                <div className="playlistEmpty">
                                    No tracks yet. Generate recommendations and add tracks!
                                </div>
                            )}
                            {playlistTracks.map((track, index) => {
                                const artists = track.artists ? track.artists.map(a => a.name).join(', ') : '';
                                const image = track.album && track.album.images && track.album.images.length > 2
                                    ? track.album.images[2].url : '';
                                const isDragOver = this.state.dragOverIndex === index && this.state.dragIndex !== index;
                                return (
                                    <div
                                        key={track.id}
                                        className={'playlistTrackRow' + (isDragOver ? ' plDragOver' : '')}
                                        draggable
                                        onDragStart={(e) => this.handleDragStart(e, index)}
                                        onDragEnd={this.handleDragEnd}
                                        onDragOver={(e) => this.handleDragOver(e, index)}
                                        onDrop={(e) => this.handleDrop(e, index)}
                                    >
                                        <span className="playlistDragHandle" title="Drag to reorder">⠿</span>
                                        <span className="playlistTrackNum">{index + 1}</span>
                                        {image && <img src={image} alt="" className="playlistTrackThumb" />}
                                        <div className="playlistTrackInfo">
                                            <span className="playlistTrackName">{track.name}</span>
                                            <span className="playlistTrackArtist">{artists}</span>
                                        </div>
                                        <button
                                            className="playlistRemoveBtn"
                                            onClick={() => this.removeTrack(track.id)}
                                        >
                                            ✕
                                        </button>
                                    </div>
                                );
                            })}
                        </div>

                        {playlistTracks.length > 0 && (
                            <div className="playlistActions">
                                {authenticated ? (
                                    <button
                                        className="savePlaylistButton"
                                        onClick={this.handleSave}
                                        disabled={saving}
                                    >
                                        {saving ? 'Saving...' : 'Save to Spotify'}
                                    </button>
                                ) : (
                                    <div className="spotifyPrompt">
                                        <p className="spotifyPromptText">Connect your Spotify account to save this playlist.</p>
                                        <button className="spotifyPromptBtn" onClick={this.props.onLogin}>
                                            <svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor">
                                                <path d="M12 0C5.4 0 0 5.4 0 12s5.4 12 12 12 12-5.4 12-12S18.66 0 12 0zm5.521 17.34c-.24.359-.66.48-1.021.24-2.82-1.74-6.36-2.101-10.561-1.141-.418.122-.779-.179-.899-.539-.12-.421.18-.78.54-.9 4.56-1.021 8.52-.6 11.64 1.32.42.18.479.659.301 1.02zm1.44-3.3c-.301.42-.841.6-1.262.3-3.239-1.98-8.159-2.58-11.939-1.38-.479.12-1.02-.12-1.14-.6-.12-.48.12-1.021.6-1.141C9.6 9.9 15 10.561 18.72 12.84c.361.181.54.78.241 1.2zm.12-3.36C15.24 8.4 8.82 8.16 5.16 9.301c-.6.179-1.2-.181-1.38-.721-.18-.601.18-1.2.72-1.381 4.26-1.26 11.28-1.02 15.721 1.621.539.3.719 1.02.419 1.56-.299.421-1.02.599-1.559.3z"/>
                                            </svg>
                                            Connect Spotify to Save
                                        </button>
                                    </div>
                                )}
                                <button className="clearPlaylistBtn" onClick={onClose}>
                                    Clear &amp; Start Fresh
                                </button>
                            </div>
                        )}
                    </React.Fragment>
                )}
            </div>
        );
    }
}

PlaylistBuilder.propTypes = {
    playlistTracks: PropTypes.array.isRequired,
    authenticated: PropTypes.bool.isRequired,
    onRemoveTrack: PropTypes.func.isRequired,
    onReorder: PropTypes.func.isRequired,
    onClear: PropTypes.func.isRequired,
    onClose: PropTypes.func.isRequired,
    playlistName: PropTypes.string.isRequired,
    playlistDescription: PropTypes.string.isRequired,
    playlistIsPublic: PropTypes.bool.isRequired,
    onNameChange: PropTypes.func.isRequired,
    onDescChange: PropTypes.func.isRequired,
    onPublicChange: PropTypes.func.isRequired
};

export default PlaylistBuilder;
